# Generated by Django 5.2.11 on 2026-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
